# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.

# See https://www.packer.io/docs/templates/hcl_templates/blocks/packer for more info
packer {
  required_plugins {
    azure = {
      source  = "github.com/hashicorp/azure"
      version = "~> 1"
    }
  }
}

# All generated input variables will be of 'string' type as this is how Packer JSON
# views them; you can change their type later on. Read the variables type
# constraints documentation
# https://www.packer.io/docs/templates/hcl_templates/variables#type-constraints for more info.
variable "azure-client-id" {
  type = string
}

variable "azure-client-secret" {
  type = string
}

variable "azure-region" {
  type = string
}

variable "azure-resource-group" {
  type = string
}

variable "azure-subscription-id" {
  type = string
}

variable "azure-tenant-id" {
  type = string
}

variable "vm-size" {
  type = string
}

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source
source "azure-arm" "autogenerated_1" {
  client_id                         = "${var.azure-client-id}"
  client_secret                     = "${var.azure-client-secret}"
  communicator                      = "winrm"
  image_offer                       = "WindowsServer"
  image_publisher                   = "MicrosoftWindowsServer"
  image_sku                         = "2019-Datacenter"
  location                          = "${var.azure-region}"
  managed_image_name                = "Win2019-Update-AllSoftware-Packer"
  managed_image_resource_group_name = "${var.azure-resource-group}"
  os_type                           = "Windows"
  subscription_id                   = "${var.azure-subscription-id}"
  tenant_id                         = "${var.azure-tenant-id}"
  vm_size                           = "${var.vm-size}"
  winrm_insecure                    = true
  winrm_timeout                     = "3m"
  winrm_use_ssl                     = true
  winrm_username                    = "packer"
}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "windows-update" {
  }

  provisioner "windows-restart" {
    restart_timeout = "15m"
  }

  provisioner "powershell" {
    script = "scripts/install_iis.ps1"
  }

  provisioner "powershell" {
    script = "scripts/install_chocolatey.ps1"
  }

  provisioner "windows-restart" {
    restart_timeout = "15m"
  }

  provisioner "powershell" {
    script = "scripts/install_chocolatey.ps1"
  }

  provisioner "powershell" {
    script = "scripts/install_software.ps1"
  }

  provisioner "powershell" {
    script = "scripts/execute_sysprep.ps1"
  }

}
