packer {
  required_plugins {
    azure = {
      source  = "github.com/hashicorp/azure"
      version = "~> 2"
    }
    windows-update = {
      source  = "github.com/rgl/windows-update"
      version = "~> 0.14.3"
    }
  }
}

variable "azure-client-id" {
  type = string
}

variable "azure-client-secret" {
  type = string
}

variable "azure-region" {
  type = string
}

variable "azure-resource-group" {
  type = string
}

variable "azure-subscription-id" {
  type = string
}

variable "azure-tenant-id" {
  type = string
}

variable "vm-size" {
  type = string
}

variable "image-name" {
  type = string
}

source "azure-arm" "autogenerated_1" {
  client_id                         = "${var.azure-client-id}"
  client_secret                     = "${var.azure-client-secret}"
  communicator                      = "winrm"
  image_offer                       = "WindowsServer"
  image_publisher                   = "MicrosoftWindowsServer"
  image_sku                         = "2019-Datacenter"
  location                          = "${var.azure-region}"
  managed_image_name                = "${var.image-name}"
  managed_image_resource_group_name = "${var.azure-resource-group}"
  os_type                           = "Windows"
  subscription_id                   = "${var.azure-subscription-id}"
  tenant_id                         = "${var.azure-tenant-id}"
  vm_size                           = "${var.vm-size}"
  winrm_insecure                    = true
  winrm_timeout                     = "3m"
  winrm_use_ssl                     = true
  winrm_username                    = "packer"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "windows-update" {
  }

  provisioner "windows-restart" {
    restart_timeout = "15m"
  }

  provisioner "powershell" {
    script = "scripts/install_iis.ps1"
  }

  provisioner "powershell" {
    script = "scripts/install_chocolatey.ps1"
  }

  provisioner "windows-restart" {
    restart_timeout = "15m"
  }

  provisioner "powershell" {
    script = "scripts/install_chocolatey.ps1"
  }

  provisioner "powershell" {
    script = "scripts/install_software.ps1"
  }

  provisioner "powershell" {
    script = "scripts/execute_sysprep.ps1"
  }
}
