choco install azure-cli -y
choco install microsoft-edge -y
choco install git.install -y
choco install netfx-4.8-devpack -y
choco install dotnet-6.0-sdk -y
choco install openssl -y
choco install powershell-core -y
choco install winrar -y
choco install notepadplusplus -y
choco install nvm -y
